### ISSUE TITLE
TODO (~6.24 월 17:00)

### ISSUE THREAD

**Issue by yminjuu** [yminjuu/TodoList-Web#5]
**TODO** : 백엔드 파트장님 API 가지고 해보기.
<전체적으로 모든 데이터 관리하도록 Home.jsx의 데이터 관리 갈아엎기>
- [x] 달력에서 날짜 클릭 가능하도록 해야함 -> 실시간으로 "현재 클릭된 날짜" 데이터 hold 해야함.
- [x] ADD TODO 에서 완료 버튼이 눌리면 현재 선택되어 있던 날짜와 함께 MY TODO LIST에 들어가는 데이터에 추가되어야 함. - create
- [x] x 표시 누르면 list에서 삭제되어 리랜더링 - delete
- [x] 수정 버튼 누르면 해당 TODO 내용이 ADD TODO로 이동, 거기서 완료 버튼 눌리면 수정된 내용으로 데이터 overwrite - edit

**API Connection**
- [x] 회원 가입
- [x] 로그인
- [x] 투두리스트 조회
- [x] 투두 작성
